### ISSUE TITLE
feature request: also return real file path

### ISSUE THREAD

**Issue by jcesarmobile** [triniwiz/capacitor-downloader#16]
At the moment the plugin returns a `path` that looks like `capacitor://path/to/file`, which is fine to be used on the webview (do fetch to it, use it as src on images or videos), but can't be used by the Filesystem plugin to copy to a permanent location.

Capacitor camera plugin has
```
path ?: string; 
webPath ?: string;
```
where `path` is the real file path in the filesystem and `webPath` is a `capacitor://` path the webview understands.

Since you are already using `path` for the  `capacitor://` path, I would't use the same names as Camera plugin as it will be a breaking change in your plugin, but maybe you can return it like `filePath` or `filesystemPath`.

**Comment by triniwiz** [comment]
Sounds good

**Comment by Fdom92** [comment]
Hi!

I was looking into download files using this plugin with Capacitor and combine this with Capacitor FileSystem to download files and save on the filesystem.

Works good but once the file is downloaded, I see the path, I can't find the file and wondering if this has something to do with that and if it's related.

If thats the case, this is going to be added to the plugin? Might I help you with this?

**Comment by KevinSleegers** [comment]
Hi @Fdom92 ,

I'm currently facing the same issue. Have you managed to solve this?
If so, would you mind sharing your code solution?

Thanks,
Kevin

**Comment by jcesarmobile** [comment]
closing since the plugin seems abandoned
