### ISSUE TITLE
TypeError: Cannot read property 'createDownload' of undefined

### ISSUE THREAD

**Issue by Eth3rnit3** [triniwiz/capacitor-downloader#5]
Hi, I have exactly the same error as the issue you closed. I use js without any framework.

I following the readme too !

**Comment by mdshadman** [comment]
> Hi, I have exactly the same error as the issue you closed. I use js without any framework.
> 
> I following the readme too !

facing the same issue

**Comment by mval1002** [comment]
When using external capacitor plugins, you need to add them to the MainActivitiy.java file as explained in the Capacitor docs. I've come across this a few times now - I hope more plugins include this step in their instructions as time goes on!

`import co.fitcom.capacitor.Downloader.DownloaderPlugin;`

this.init function: 
`add(DownloaderPlugin.class);`

**Comment by mdshadman** [comment]
Hey mval1002 thank you for your help and time, it solved my problem.
Can you please update your documentation with all the required information
so that people like us don't get issues.
Thanks in advance

**Comment by mval1002** [comment]
Glad I could help!

I'm not the developer of this plugin, so I can't update any documentation for it. As I mentioned in my other comment, I hope as the Capacitor platform matures, more of the developers will include that step in their instructions. As it stands, it's buried at the bottom of the Android Plugin section of the Capacitor docs, and on top of that its not always easy to find the import path. I've seen this same issue come up in a number of Community Plugins that I've looked at, so I try to help out!
