### ISSUE TITLE
sdk incompatible

### ISSUE THREAD

**Issue by strogof** [triniwiz/capacitor-downloader#9]
Hi, 
thanks for share your work,
what can i do to solve this...

Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 25 declared in library [:capacitor-cordova-android-plugins] D:\ordiNetTabletCapacitor\android\capacitor-cordova-android-plugins\build\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 25,
		or use tools:overrideLibrary="capacitor.android.plugins" to force usage (may lead to runtime failures)

**Comment by BryanYin** [comment]
same issue here. I just move from cordova to capacitor, but failed in replace HTTP with this one. I noticed this [fix](https://github.com/triniwiz/capacitor-downloader/commit/3bf3b47e763753830cad28f854ff8c08ac400c8d) upgrades miniSDK to 25, could you check if we can still use version 21?
